"""
All padel clubs in Poland on kluby.org with scrapeable schedules.
74 clubs, sorted alphabetically by slug.
"""

CLUBS = {
    "ahoj-padel": {"name": "Ahoj Padel", "slug": "ahoj-padel", "courts": 4, "city": "Niepolomice"},
    "akademia-padla": {"name": "Akademia Padla", "slug": "akademia-padla", "courts": 4, "city": "Poznan"},
    "amber-park": {"name": "Amber Park Spa", "slug": "amber-park", "courts": 1, "city": "Niechorze"},
    "asaja-sport": {"name": "ASAJA SPORT", "slug": "asaja-sport", "courts": 1, "city": "Rogozino"},
    "bajada-sports-club": {"name": "Bajada Padel Club", "slug": "bajada-sports-club", "courts": 3, "city": "Krakow"},
    "baltic-padel-club": {"name": "Baltic Padel Club", "slug": "baltic-padel-club", "courts": 9, "city": "Gdynia"},
    "baza-padel-club": {"name": "Baza Padel Club", "slug": "baza-padel-club", "courts": 5, "city": "Grudziadz"},
    "baza-sport-suchy-dwor": {"name": "BAZA SPORT SUCHY DWOR", "slug": "baza-sport-suchy-dwor", "courts": 2, "city": "Suchy Dwor"},
    "bulwary-wislane": {"name": "Padel4All Bulwary Wislane", "slug": "bulwary-wislane", "courts": 1, "city": "Warszawa"},
    "calisia-padel": {"name": "Calisia Padel", "slug": "calisia-padel", "courts": 7, "city": "Kalisz"},
    "carthagowola": {"name": "Carthagowola Klub Padel", "slug": "carthagowola", "courts": 2, "city": "Turbia"},
    "chorzowska-liga-padla": {"name": "Chorzowska Liga Padla", "slug": "chorzowska-liga-padla", "courts": 2, "city": "Chorzow"},
    "city-padel-torun": {"name": "City Padel Torun", "slug": "city-padel-torun", "courts": 5, "city": "Torun"},
    "csr-platinum": {"name": "CSR Platinum", "slug": "csr-platinum", "courts": 2, "city": "Rybnik"},
    "fabryka-energii": {"name": "Fabryka Energii", "slug": "fabryka-energii", "courts": 4, "city": "Szczecin"},
    "fast-tennis-gdanska": {"name": "Fast Tennis Padel Club", "slug": "fast-tennis-gdanska", "courts": 2, "city": "Bydgoszcz"},
    "fiesta-padel": {"name": "Fiesta Padel", "slug": "fiesta-padel", "courts": 3, "city": "Wroclaw"},
    "gdynia-padel-club": {"name": "GDYNIA PADEL CLUB", "slug": "gdynia-padel-club", "courts": 6, "city": "Gdynia"},
    "happy-padel": {"name": "Happy Padel", "slug": "happy-padel", "courts": 3, "city": "Warszawa"},
    "interpadel-gdynia": {"name": "InterPadel Gdynia", "slug": "interpadel-gdynia", "courts": 4, "city": "Gdynia"},
    "interpadel-poznan": {"name": "Interpadel Poznan", "slug": "interpadel-poznan", "courts": 4, "city": "Poznan"},
    "interpadel-torun": {"name": "InterPadel Torun", "slug": "interpadel-torun", "courts": 1, "city": "Torun"},
    "interpadel-warszawa": {"name": "InterPadel Warszawa", "slug": "interpadel-warszawa", "courts": 9, "city": "Warszawa"},
    "kortmax": {"name": "Kortmax", "slug": "kortmax", "courts": 2, "city": "Blonie"},
    "leo-padel": {"name": "LEO PADEL", "slug": "leo-padel", "courts": 2, "city": "Trabki Wielkie"},
    "loba-padel": {"name": "Loba Padel", "slug": "loba-padel", "courts": 8, "city": "Warszawa"},
    "lomianki-padel-club": {"name": "Lomianki Padel Club", "slug": "lomianki-padel-club", "courts": 4, "city": "Lomianki"},
    "mana-padel": {"name": "Mana Padel", "slug": "mana-padel", "courts": 8, "city": "Warszawa"},
    "mera": {"name": "WKT Mera", "slug": "mera", "courts": 2, "city": "Warszawa"},
    "miedzeszyn": {"name": "Klub Miedzeszyn", "slug": "miedzeszyn", "courts": 2, "city": "Warszawa"},
    "moris-katowicka": {"name": "MORIS Chorzow", "slug": "moris-katowicka", "courts": 2, "city": "Chorzow"},
    "mosir-slowian": {"name": "MOSiR Slowian", "slug": "mosir-slowian", "courts": 1, "city": "Katowice"},
    "nowosolna": {"name": "Korty Nowosolna", "slug": "nowosolna", "courts": 1, "city": "Lodz"},
    "one-padel": {"name": "One Padel Center", "slug": "one-padel", "courts": 4, "city": "Bielsko-Biala"},
    "padbox": {"name": "PADBOX STADION", "slug": "padbox", "courts": 5, "city": "Gdansk"},
    "padbox-kartuska": {"name": "PADBOX KARTUSKA", "slug": "padbox-kartuska", "courts": 5, "city": "Gdansk"},
    "padel-arena": {"name": "Padel Arena Limanowa", "slug": "padel-arena", "courts": 3, "city": "Limanowa"},
    "padel-center-academy": {"name": "Padel Center Academy", "slug": "padel-center-academy", "courts": 9, "city": "Katowice"},
    "padel-club-szczecin": {"name": "Padel Club Szczecin", "slug": "padel-club-szczecin", "courts": 5, "city": "Szczecin"},
    "padel-factory": {"name": "Padel Factory", "slug": "padel-factory", "courts": 2, "city": "Nowy Sacz"},
    "padel-gdansk": {"name": "Padel Gdansk", "slug": "padel-gdansk", "courts": 6, "city": "Gdansk"},
    "padel-house-krakow": {"name": "Padel House Krakow", "slug": "padel-house-krakow", "courts": 4, "city": "Krakow"},
    "padel-jaworzno": {"name": "Padel Jaworzno VIA Sport", "slug": "padel-jaworzno", "courts": 4, "city": "Jaworzno"},
    "padel-lodz": {"name": "Padel Lodz", "slug": "padel-lodz", "courts": 2, "city": "Lodz"},
    "padel-on": {"name": "Padel On", "slug": "padel-on", "courts": 4, "city": "Pszczyna"},
    "padel-park": {"name": "Padel Park", "slug": "padel-park", "courts": 4, "city": "Pruszcz Gdanski"},
    "padel-park-bydgoszcz": {"name": "Padel Park Bydgoszcz", "slug": "padel-park-bydgoszcz", "courts": 2, "city": "Bydgoszcz"},
    "padel-pl-wroclaw": {"name": "Padel PL Wroclaw", "slug": "padel-pl-wroclaw", "courts": 4, "city": "Wroclaw"},
    "padel-point-bialystok": {"name": "Padel Point Bialystok", "slug": "padel-point-bialystok", "courts": 5, "city": "Bialystok"},
    "padel-point-lublin": {"name": "Padel Point Lublin", "slug": "padel-point-lublin", "courts": 5, "city": "Lublin"},
    "padel-radom": {"name": "Padel Radom", "slug": "padel-radom", "courts": 4, "city": "Radom"},
    "padel-score-elblag": {"name": "Padel Score Elblag", "slug": "padel-score-elblag", "courts": 2, "city": "Elblag"},
    "padel-team-bytom": {"name": "Padel Team Bytom", "slug": "padel-team-bytom", "courts": 4, "city": "Bytom"},
    "padel-team-tychy": {"name": "Padel Team Tychy", "slug": "padel-team-tychy", "courts": 4, "city": "Tychy"},
    "padel-team-zabrze": {"name": "Padel Team Zabrze", "slug": "padel-team-zabrze", "courts": 4, "city": "Zabrze"},
    "padelbox-rzeszow": {"name": "PadelBOX Rzeszow", "slug": "padelbox-rzeszow", "courts": 2, "city": "Rzeszow"},
    "padelmania": {"name": "Padelmania", "slug": "padelmania", "courts": 3, "city": "Dabrowa Gornicza"},
    "payments-lights": {"name": "PAYMENTS & LIGHTS", "slug": "payments-lights", "courts": 5, "city": "Lubsko"},
    "pisz-point": {"name": "Klub Tenisowy Pisz-Point", "slug": "pisz-point", "courts": 2, "city": "Pisz"},
    "plek-poznan": {"name": "PLEK Poznan", "slug": "plek-poznan", "courts": 5, "city": "Poznan"},
    "pogoria-padel-club": {"name": "Pogoria Padel Club", "slug": "pogoria-padel-club", "courts": 2, "city": "Dabrowa Gornicza"},
    "prestigecourt": {"name": "Otwocka Akademia Tenisa", "slug": "prestigecourt", "courts": 1, "city": "Otwock"},
    "propadel": {"name": "ProPadel Jutrzenki", "slug": "propadel", "courts": 5, "city": "Warszawa"},
    "pura-padel-pickleball": {"name": "PURA PADEL", "slug": "pura-padel-pickleball", "courts": 5, "city": "Bydgoszcz"},
    "rakietmania": {"name": "Rakietmania", "slug": "rakietmania", "courts": 1, "city": "Lublin"},
    "rancho-padel-club": {"name": "Rancho Padel Club", "slug": "rancho-padel-club", "courts": 5, "city": "Mala Nieszawka"},
    "sporteum": {"name": "Sporteum", "slug": "sporteum", "courts": 2, "city": "Warszawa"},
    "stacja-padel": {"name": "Stacja Padel", "slug": "stacja-padel", "courts": 5, "city": "Lodz"},
    "tenes": {"name": "TENES Klub Sportowy", "slug": "tenes", "courts": 3, "city": "Jawczyce"},
    "teniswil": {"name": "TenisWil", "slug": "teniswil", "courts": 3, "city": "Warszawa"},
    "toro-padel": {"name": "Toro Padel", "slug": "toro-padel", "courts": 6, "city": "Warszawa"},
    "ultra-padel-gliwice": {"name": "ULTRA PADEL Gliwice", "slug": "ultra-padel-gliwice", "courts": 4, "city": "Gliwice"},
    "viva-padel-katowice": {"name": "VIVA PADEL KATOWICE", "slug": "viva-padel-katowice", "courts": 8, "city": "Katowice"},
    "warsaw-padel-club": {"name": "Warsaw Padel Club", "slug": "warsaw-padel-club", "courts": 10, "city": "Warszawa"},
}

DEFAULT_CLUB = "loba-padel"
